### ISSUE TITLE
Erro no namespace Xamarin.Forms

### ISSUE THREAD

**Issue by victgo92** [MonkeyNights/xamarin-teste-seu-ambiente#10]
<img width="1104" alt="screen shot 2017-04-10 at 22 58 53" src="https://cloud.githubusercontent.com/assets/27257311/24889658/95e908c6-1e41-11e7-984a-4fece46c3c6a.png">

Baixei o projeto do git, Atualizei todos os pacotes, porém não foi possível a compilação do projeto.

**Comment by FabaoAnalista** [comment]
Reveja seus pacotes framwork

**Comment by victgo92** [comment]
Ja deletei os pacotes e adicionei novamente e o erro persiste

**Comment by FabaoAnalista** [comment]
Agradeço pois estava dando esse erro no pacote xamarins forma.

Em 17/04/2017 8:12 PM, "victgo92" <notifications@github.com> escreveu:

**Comment by victgo92** [comment]
Consegui resolver, Baixei o projeto novamente e não dei update nos pacotes. Apenas atualizei o Xamarin.Forms e deu certo. Muito Obrigado!!

**Comment by FabaoAnalista** [comment]
Vc usou o NuGet update somente no xamarin forms foi isso né?

Em 17/04/2017 8:17 PM, "victgo92" <notifications@github.com> escreveu:

Consegui resolver, Baixei o projeto novamente e não dei update nos pacotes.
Apenas atualizei o Xamarin.Forms e deu certo. Muito Obrigado!!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MonkeyNights/xamarin-teste-seu-ambiente/issues/10#issuecomment-294622840>,
or mute the thread
